name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}

  strategy:
    fail-fast: false
    matrix:
      os: [windows-latest, macos-latest]

  steps:
    - name: Check out git repository
      uses: actions/checkout@v1.0.0

    - name: Install Node.js
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Cleanup Artifacts for Windows
      if: matrix.os == 'windows-latest'
      run: npm run build:win

    - name: Cleanup Artifacts for MacOS
      if: matrix.os == 'macos-latest'
      run: npm run build:mac
