name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref }}
          path: dist

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*,
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
