name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: install/release Electron app
        run: npm install

      - name: Build/release Electron windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Build/release Electron MacOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
