name: Build

on:
  push:
    branches:
      - master

jobs:
  container-test-job:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
runs-on: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Cleanup Artifacts for Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: Cleanup Artifacts for MacOS
        if: matrix.os == 'macos-latest'
        run: npm run build:mac
